name: Packer Build

on:
  push:
    branches:
      - master  # Ensure this matches your default branch
  pull_request:
    branches:
      - master  # Ensure this matches your default branch
  workflow_dispatch:
jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl -fsSL -o packer.zip https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          rm packer.zip  # Cleanup ZIP file after installation
          packer --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "ap-southeast-2"  # Optionally include this if you're using a specific region

      - name: Run Packer Build
        run: |
          packer init aws-ubuntu.pkr.hcl
          packer validate aws-ubuntu.pkr.hcl
          packer build aws-ubuntu.pkr.hcl
